name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: jorelali/setup-elm@v2
        with:
          elm-version: 0.19.1
      - run: npm install -g elm-test
      - run: elm make
      - run: elm-test
